spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  aws:
    region: ${AWS_REGION:eu-west-1}
    s3:
      bucket: ${S3_BUCKET:customer-statements}
  sqs:
    queue-name: ${SQS_QUEUE:statement-ingestion-queue}
